[Icon Theme]
Name=YAMIS-enlarged
Inherits=TokyoNight-Files,Adwaita,AdwaitaLegacy,breeze-dark,hicolor
Comment=YAMIS Enlarged - App icons with TokyoNight-Files for file/folder icons and Adwaita for UI tools

DisplayDepth=32
FollowsColorScheme=true
Example=x-directory-normal

KDE-Extensions=.svg

Directories=apps/16,apps/scalable

[apps/16]
Size=16
Context=Applications
Type=Scalable
MinSize=8
MaxSize=24

[apps/scalable]
Size=128
Context=Applications
Type=Scalable
MinSize=8
MaxSize=512
