# ── Section ──
# Background
background {
    monitor =
    path = ~/code/arch-theme/wallpapers/satisfaction_hires_lock_final.png
    blur_passes = 2
    blur_size = 5
}

# ── Section ──
# Input Field
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(39c5bbee)
    inner_color = rgba(1a1b26ee)
    font_color = rgb(c0caf5)
    fade_on_empty = false
    placeholder_text = Password...
    rounding = 10
    position = 0, -80
    halign = center
    valign = center
}

# ── Section ──
# Time Label
label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = IBM Plex Sans SmBld
    color = rgba(c0caf5ee)
    position = 0, 80
    halign = center
    valign = center
}
