[Icon Theme]
Name=TokyoNight-Files
Comment=Tokyo Night icons strictly for folders (places), files (mimetypes), and drives (devices)
Inherits=Adwaita,AdwaitaLegacy,breeze-dark,hicolor

Example=folder

FollowsColorScheme=true

DesktopDefault=48
DesktopSizes=16,22,24,32,48,64
ToolbarDefault=22
ToolbarSizes=16,22,24,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,24,32,48
SmallDefault=16
SmallSizes=16,22,24,32,48
PanelDefault=48
PanelSizes=16,22,24,32,48,64
DialogDefault=48
DialogSizes=16,22,24,32,48,64

# Directory list
Directories=16x16/devices,16x16/mimetypes,16x16/places,16x16@2x/devices,16x16@2x/mimetypes,16x16@2x/places,22x22/devices,22x22/mimetypes,22x22/places,22x22@2x/devices,22x22@2x/mimetypes,22x22@2x/places,24x24/devices,24x24/mimetypes,24x24/places,24x24@2x/devices,24x24@2x/mimetypes,24x24@2x/places,32x32/devices,32x32/mimetypes,32x32/places,32x32@2x/devices,32x32@2x/mimetypes,32x32@2x/places,48x48/devices,48x48/mimetypes,48x48/places,48x48@2x/devices,48x48@2x/mimetypes,48x48@2x/places,64x64/devices,64x64/mimetypes,64x64/places,64x64@2x/devices,64x64@2x/mimetypes,64x64@2x/places,symbolic/devices,symbolic/mimetypes,symbolic/places

[16x16/devices]
Context=Devices
Size=16
Type=Fixed

[16x16/mimetypes]
Context=MimeTypes
Size=16
Type=Fixed

[16x16/places]
Context=Places
Size=16
Type=Fixed

[16x16@2x/devices]
Context=Devices
Size=16
Scale=2
Type=Fixed

[16x16@2x/mimetypes]
Context=MimeTypes
Size=16
Scale=2
Type=Fixed

[16x16@2x/places]
Context=Places
Size=16
Scale=2
Type=Fixed

[22x22/devices]
Context=Devices
Size=22
Type=Fixed

[22x22/mimetypes]
Context=MimeTypes
Size=22
Type=Fixed

[22x22/places]
Context=Places
Size=22
Type=Fixed

[22x22@2x/devices]
Context=Devices
Size=22
Scale=2
Type=Fixed

[22x22@2x/mimetypes]
Context=MimeTypes
Size=22
Scale=2
Type=Fixed

[22x22@2x/places]
Context=Places
Size=22
Scale=2
Type=Fixed

[24x24/devices]
Context=Devices
Size=24
Type=Fixed

[24x24/mimetypes]
Context=MimeTypes
Size=24
Type=Fixed

[24x24/places]
Context=Places
Size=24
Type=Fixed

[24x24@2x/devices]
Context=Devices
Size=24
Scale=2
Type=Fixed

[24x24@2x/mimetypes]
Context=MimeTypes
Size=24
Scale=2
Type=Fixed

[24x24@2x/places]
Context=Places
Size=24
Scale=2
Type=Fixed

[32x32/devices]
Context=Devices
Size=32
Type=Fixed

[32x32/mimetypes]
Context=MimeTypes
Size=32
Type=Fixed

[32x32/places]
Context=Places
Size=32
Type=Fixed

[32x32@2x/devices]
Context=Devices
Size=32
Scale=2
Type=Fixed

[32x32@2x/mimetypes]
Context=MimeTypes
Size=32
Scale=2
Type=Fixed

[32x32@2x/places]
Context=Places
Size=32
Scale=2
Type=Fixed

[48x48/devices]
Context=Devices
Size=48
Type=Fixed

[48x48/mimetypes]
Context=MimeTypes
Size=48
Type=Fixed

[48x48/places]
Context=Places
Size=48
Type=Fixed

[48x48@2x/devices]
Context=Devices
Size=48
Scale=2
Type=Fixed

[48x48@2x/mimetypes]
Context=MimeTypes
Size=48
Scale=2
Type=Fixed

[48x48@2x/places]
Context=Places
Size=48
Scale=2
Type=Fixed

[64x64/devices]
Context=Devices
Size=64
Type=Fixed

[64x64/mimetypes]
Context=MimeTypes
Size=64
Type=Fixed

[64x64/places]
Context=Places
Size=64
Type=Fixed

[64x64@2x/devices]
Context=Devices
Size=64
Scale=2
Type=Fixed

[64x64@2x/mimetypes]
Context=MimeTypes
Size=64
Scale=2
Type=Fixed

[64x64@2x/places]
Context=Places
Size=64
Scale=2
Type=Fixed

[symbolic/devices]
Context=Devices
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/mimetypes]
Context=MimeTypes
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/places]
Context=Places
Size=16
MinSize=16
MaxSize=512
Type=Scalable
